unique_ids:
  assets:
    standard-page.html: DYLYRTWGMX2CUQUNGVZV2U7GIO6TIDQU
    theme.css: ZKAHJJC7PD5WWGU46IFABZMMZ6EOBCFH
  forms:
    MyPageForm: S76LQ2G6CRIO7S2JI3EHDUZARKPSS3U6
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1761155829818451232306200.1683'
